/* ---------------------------------------------------------------------------
   The Library — baked snapshot of the shelf log.

   Source of truth is the Google Sheet; this file is the copy that ships with the
   site so the page paints instantly, works offline, and can never render empty.
   Styles/library.js re-reads the sheet after first paint and quietly swaps in any
   changes, so re-baking this file is optional housekeeping — not a requirement
   for a new book to show up on the site.

   Columns: [ Title, Author, Genre, Release Year, Rating ]
   ("Copies Seen" and "Image #" are intentionally not included.)

   Rating is Pob's own 0-5 score. The sheet has no Rating column yet, so the
   rows below carry four values and every book reads as unrated. Add a column
   headed "Rating" to the sheet and the live sync picks it up on the next page
   load -- columns are located by header name, so its position does not matter.

   To re-bake (341 books as of 2026-09-11):
     curl -sSL "https://docs.google.com/spreadsheets/d/1LSyUoNO50mpBUlmAEt9lHR9n7XVE7jGSeH29lT9m1Ik/gviz/tq?tqx=out:csv" -o books.csv
   then ask Claude to regenerate this file from it.
--------------------------------------------------------------------------- */
window.LIBRARY_SEED = [
  ["The Prince", "Niccolo Machiavelli", "Political Philosophy", "1532"],
  ["Romeo and Juliet", "William Shakespeare", "Drama", "1597"],
  ["Macbeth", "William Shakespeare", "Drama", "1606"],
  ["Gulliver's Travels", "Jonathan Swift", "Classic / Satire", "1726"],
  ["Candide", "Voltaire", "Classic", "1759"],
  ["Grimm's Complete Fairy Tales", "Brothers Grimm", "Folklore / Classic", "1812"],
  ["Pride and Prejudice", "Jane Austen", "Classic", "1813"],
  ["Frankenstein", "Mary Shelley", "Gothic / Science Fiction", "1818"],
  ["Best-Loved Fairy Tales", "Hans Christian Andersen", "Folklore / Classic", "1835"],
  ["Wuthering Heights", "Emily Bronte", "Classic", "1847"],
  ["Great Expectations", "Charles Dickens", "Classic", "1861"],
  ["Crime and Punishment", "Fyodor Dostoevsky", "Classic", "1866"],
  ["The Adventures of Huckleberry Finn", "Mark Twain", "Classic", "1884"],
  ["Strange Case of Dr Jekyll and Mr Hyde", "Robert Louis Stevenson", "Classic", "1886"],
  ["The Death of Ivan Ilyich", "Leo Tolstoy", "Classic", "1886"],
  ["The War of the Worlds", "H. G. Wells", "Science Fiction", "1898"],
  ["The Extraordinary Adventures of Arsene Lupin", "Maurice Leblanc", "Classic Mystery", "1907"],
  ["Arsene Lupin vs Herlock Sholmes", "Maurice Leblanc", "Classic Mystery", "1908"],
  ["The Hollow Needle", "Maurice Leblanc", "Classic Mystery", "1909"],
  ["813", "Maurice Leblanc", "Classic Mystery", "1910"],
  ["The Crystal Stopper", "Maurice Leblanc", "Classic Mystery", "1912"],
  ["The Confessions of Arsene Lupin", "Maurice Leblanc", "Classic Mystery", "1913"],
  ["The Teeth of the Tiger", "Maurice Leblanc", "Classic Mystery", "1914"],
  ["The Metamorphosis", "Franz Kafka", "Classic", "1915"],
  ["The Golden Triangle", "Maurice Leblanc", "Classic Mystery", "1917"],
  ["Demian", "Hermann Hesse", "Classic", "1919"],
  ["The Sun Also Rises", "Ernest Hemingway", "Classic", "1926"],
  ["The Call of Cthulhu", "H. P. Lovecraft", "Horror", "1928"],
  ["All Quiet on the Western Front", "Erich Maria Remarque", "Classic", "1929"],
  ["Brave New World", "Aldous Huxley", "Science Fiction", "1932"],
  ["How to Win Friends and Influence People", "Dale Carnegie", "Self-Help", "1936"],
  ["Of Mice and Men", "John Steinbeck", "Classic", "1937"],
  ["The Hobbit", "J. R. R. Tolkien", "Fantasy", "1937"],
  ["The Little Prince", "Antoine de Saint-Exupery", "Classic / Fable", "1943"],
  ["Earth Abides", "George R. Stewart", "Science Fiction", "1949"],
  ["Nineteen Eighty-Four", "George Orwell", "Science Fiction", "1949"],
  ["The Martian Chronicles", "Ray Bradbury", "Science Fiction", "1950"],
  ["The Catcher in the Rye", "J. D. Salinger", "Literary Fiction", "1951"],
  ["The Old Man and the Sea", "Ernest Hemingway", "Classic", "1952"],
  ["Fahrenheit 451", "Ray Bradbury", "Science Fiction", "1953"],
  ["The Crucible", "Arthur Miller", "Drama", "1953"],
  ["The Fellowship of the Ring", "J. R. R. Tolkien", "Fantasy", "1954"],
  ["The Two Towers", "J. R. R. Tolkien", "Fantasy", "1954"],
  ["A View from the Bridge", "Arthur Miller", "Drama", "1955"],
  ["The Return of the King", "J. R. R. Tolkien", "Fantasy", "1955"],
  ["On the Road", "Jack Kerouac", "Literary Fiction", "1957"],
  ["A Canticle for Leibowitz", "Walter M. Miller Jr.", "Science Fiction", "1959"],
  ["To Kill a Mockingbird", "Harper Lee", "Classic", "1960"],
  ["Catch-22", "Joseph Heller", "Satire", "1961"],
  ["One Day in the Life of Ivan Denisovich", "Aleksandr Solzhenitsyn", "Classic", "1962"],
  ["One Flew Over the Cuckoo's Nest", "Ken Kesey", "Literary Fiction", "1962"],
  ["Silent Spring", "Rachel Carson", "Nonfiction / Science", "1962"],
  ["We Have Always Lived in the Castle", "Shirley Jackson", "Gothic", "1962"],
  ["One Hundred Years of Solitude", "Gabriel Garcia Marquez", "Literary Fiction", "1967"],
  ["A Wizard of Earthsea", "Ursula K. Le Guin", "Fantasy", "1968"],
  ["Dune Messiah", "Frank Herbert", "Science Fiction", "1969"],
  ["Slaughterhouse-Five", "Kurt Vonnegut", "Satire", "1969"],
  ["The Left Hand of Darkness", "Ursula K. Le Guin", "Science Fiction", "1969"],
  ["Thirteen Days", "Robert F. Kennedy", "History", "1969"],
  ["The Tombs of Atuan", "Ursula K. Le Guin", "Fantasy", "1971"],
  ["The Farthest Shore", "Ursula K. Le Guin", "Fantasy", "1972"],
  ["Breakfast of Champions", "Kurt Vonnegut", "Satire", "1973"],
  ["Children of Dune", "Frank Herbert", "Science Fiction", "1976"],
  ["The Missing Piece", "Shel Silverstein", "Picture Book", "1976"],
  ["Ceremony", "Leslie Marmon Silko", "Literary Fiction", "1977"],
  ["The Silmarillion", "J. R. R. Tolkien", "Fantasy", "1977"],
  ["The Snow Leopard", "Peter Matthiessen", "Nonfiction / Travel", "1978"],
  ["The Stand", "Stephen King", "Horror", "1978"],
  ["If on a Winter's Night a Traveler", "Italo Calvino", "Literary Fiction", "1979"],
  ["Positioning", "Al Ries and Jack Trout", "Business / Marketing", "1981"],
  ["The Dark Tower: The Gunslinger", "Stephen King", "Fantasy / Western", "1982"],
  ["Neuromancer", "William Gibson", "Science Fiction", "1984"],
  ["Strategic Market Management", "David A. Aaker", "Business", "1984"],
  ["Surely You're Joking, Mr. Feynman!", "Richard P. Feynman", "Memoir / Science", "1985"],
  ["White Noise", "Don DeLillo", "Literary Fiction", "1985"],
  ["Burning Chrome", "William Gibson", "Science Fiction", "1986"],
  ["Replay", "Ken Grimwood", "Science Fiction", "1986"],
  ["The Broom of the System", "David Foster Wallace", "Literary Fiction", "1987"],
  ["The Decagon House Murders", "Yukito Ayatsuji", "Mystery", "1987"],
  ["Watchmen", "Alan Moore and Dave Gibbons", "Graphic Novel", "1987"],
  ["Mona Lisa Overdrive", "William Gibson", "Science Fiction", "1988"],
  ["The Alchemist", "Paulo Coelho", "Fiction", "1988"],
  ["The 7 Habits of Highly Effective People", "Stephen R. Covey", "Self-Help", "1989"],
  ["The Joy Luck Club", "Amy Tan", "Literary Fiction", "1989"],
  ["The Sandman", "Neil Gaiman", "Graphic Novel", "1989"],
  ["Maus", "Art Spiegelman", "Graphic Novel", "1991"],
  ["Parable of the Sower", "Octavia E. Butler", "Science Fiction", "1993"],
  ["60 Seconds and You're Hired!", "Robin Ryan", "Career / Nonfiction", "1994"],
  ["Longitude", "Dava Sobel", "Nonfiction / History", "1995"],
  ["The E-Myth Revisited", "Michael E. Gerber", "Business", "1995"],
  ["A Book of Luminous Things", "Czeslaw Milosz (ed.)", "Poetry", "1996"],
  ["Death and the Penguin", "Andrey Kurkov", "Fiction", "1996"],
  ["Infinite Jest", "David Foster Wallace", "Literary Fiction", "1996"],
  ["Into the Wild", "Jon Krakauer", "Nonfiction", "1996"],
  ["Kingdom Come", "Mark Waid and Alex Ross", "Graphic Novel", "1996"],
  ["The Millionaire Next Door", "Thomas J. Stanley and William D. Danko", "Personal Finance", "1996"],
  ["The Sparrow", "Mary Doria Russell", "Science Fiction", "1996"],
  ["Time: Great People of the 20th Century", "Time-Life", "History", "1996"],
  ["A Supposedly Fun Thing I'll Never Do Again", "David Foster Wallace", "Essays", "1997"],
  ["Guns, Germs, and Steel", "Jared Diamond", "Nonfiction / History", "1997"],
  ["The Four Agreements", "Don Miguel Ruiz", "Self-Help", "1997"],
  ["Children of God", "Mary Doria Russell", "Science Fiction", "1998"],
  ["Parable of the Talents", "Octavia E. Butler", "Science Fiction", "1998"],
  ["Short Stories in French (Penguin Parallel Text)", "Richard Coward (ed.)", "Language Learning", "1999"],
  ["The Perks of Being a Wallflower", "Stephen Chbosky", "YA", "1999"],
  ["The Worst-Case Scenario Survival Handbook", "Joshua Piven and David Borgenicht", "Humor / Reference", "1999"],
  ["Angels and Demons", "Dan Brown", "Thriller", "2000"],
  ["American Gods", "Neil Gaiman", "Fantasy", "2001"],
  ["The Secret Life of Bees", "Sue Monk Kidd", "Fiction", "2001"],
  ["Kafka on the Shore", "Haruki Murakami", "Literary Fiction", "2002"],
  ["Stories of Your Life and Others", "Ted Chiang", "Science Fiction (stories)", "2002"],
  ["A Short History of Nearly Everything", "Bill Bryson", "Popular Science", "2003"],
  ["Great Tales from English History", "Robert Lacey", "History", "2003"],
  ["The Curious Incident of the Dog in the Night-Time", "Mark Haddon", "Fiction", "2003"],
  ["The Five People You Meet in Heaven", "Mitch Albom", "Fiction", "2003"],
  ["Cloud Atlas", "David Mitchell", "Literary Fiction", "2004"],
  ["They Don't Teach Corporate in College", "Alexandra Levit", "Career / Nonfiction", "2004"],
  ["A Briefer History of Time", "Stephen Hawking", "Popular Science", "2005"],
  ["Collapse", "Jared Diamond", "Nonfiction / History", "2005"],
  ["Extremely Loud and Incredibly Close", "Jonathan Safran Foer", "Literary Fiction", "2005"],
  ["The Book Thief", "Markus Zusak", "Historical Fiction", "2005"],
  ["The Girl with the Dragon Tattoo", "Stieg Larsson", "Crime Thriller", "2005"],
  ["Stumbling on Happiness", "Daniel Gilbert", "Psychology", "2006"],
  ["The Girl Who Played with Fire", "Stieg Larsson", "Crime Thriller", "2006"],
  ["A Thousand Splendid Suns", "Khaled Hosseini", "Fiction", "2007"],
  ["Spider-Man: Family Ties", "Marvel", "Graphic Novel", "2007"],
  ["StrengthsFinder 2.0", "Tom Rath", "Business", "2007"],
  ["The Complete Illustrated History of Ancient Greece", "Nigel Rodgers", "History", "2007"],
  ["The Girl Who Kicked the Hornet's Nest", "Stieg Larsson", "Crime Thriller", "2007"],
  ["The Name of the Wind", "Patrick Rothfuss", "Fantasy", "2007"],
  ["Anathem", "Neal Stephenson", "Science Fiction", "2008"],
  ["Outliers", "Malcolm Gladwell", "Nonfiction", "2008"],
  ["Paper Towns", "John Green", "YA", "2008"],
  ["The Dark Forest", "Cixin Liu", "Science Fiction", "2008"],
  ["The Hunger Games", "Suzanne Collins", "YA Dystopian", "2008"],
  ["The Last Lecture", "Randy Pausch", "Memoir", "2008"],
  ["The Three-Body Problem", "Cixin Liu", "Science Fiction", "2008"],
  ["Catching Fire", "Suzanne Collins", "YA Dystopian", "2009"],
  ["I Will Teach You to Be Rich", "Ramit Sethi", "Personal Finance", "2009"],
  ["Start with Why", "Simon Sinek", "Business", "2009"],
  ["The 100-Year-Old Man Who Climbed Out the Window and Disappeared", "Jonas Jonasson", "Fiction", "2009"],
  ["The Book of Basketball", "Bill Simmons", "Sports", "2009"],
  ["The Lost Symbol", "Dan Brown", "Thriller", "2009"],
  ["A Dog's Purpose", "W. Bruce Cameron", "Fiction", "2010"],
  ["An Object of Beauty", "Steve Martin", "Fiction", "2010"],
  ["Attached", "Amir Levine and Rachel Heller", "Psychology", "2010"],
  ["Death's End", "Cixin Liu", "Science Fiction", "2010"],
  ["Mockingjay", "Suzanne Collins", "YA Dystopian", "2010"],
  ["The Truth About Leadership", "James Kouzes and Barry Posner", "Business", "2010"],
  ["Changing on the Job", "Jennifer Garvey Berger", "Business", "2011"],
  ["Fifty Shades of Grey", "E. L. James", "Romance", "2011"],
  ["HBR's 10 Must Reads on Leadership", "Harvard Business Review", "Business", "2011"],
  ["HBR's 10 Must Reads on Managing People", "Harvard Business Review", "Business", "2011"],
  ["Is Everyone Hanging Out Without Me?", "Mindy Kaling", "Memoir / Humor", "2011"],
  ["Models", "Mark Manson", "Self-Help", "2011"],
  ["Poor Economics", "Abhijit Banerjee and Esther Duflo", "Economics", "2011"],
  ["Shade It Black", "Jess Goodell with John Hearn", "Memoir", "2011"],
  ["The Cultural Intelligence Difference", "David Livermore", "Business", "2011"],
  ["The Lean Startup", "Eric Ries", "Business", "2011"],
  ["The Martian", "Andy Weir", "Science Fiction", "2011"],
  ["The Millionaire Fastlane", "MJ DeMarco", "Business", "2011"],
  ["The Pun Also Rises", "John Pollack", "Nonfiction / Language", "2011"],
  ["Thinking, Fast and Slow", "Daniel Kahneman", "Psychology", "2011"],
  ["A Dog's Journey", "W. Bruce Cameron", "Fiction", "2012"],
  ["A Man Called Ove", "Fredrik Backman", "Literary Fiction", "2012"],
  ["A Short Stay in Hell", "Steven L. Peck", "Science Fiction", "2012"],
  ["Fifty Shades Darker", "E. L. James", "Romance", "2012"],
  ["Fifty Shades Freed", "E. L. James", "Romance", "2012"],
  ["Leadership 2.0", "Travis Bradberry and Jean Greaves", "Business", "2012"],
  ["Me Before You", "Jojo Moyes", "Romance", "2012"],
  ["Positive Intelligence", "Shirzad Chamine", "Business", "2012"],
  ["Subliminal", "Leonard Mlodinow", "Popular Science", "2012"],
  ["The Fault in Our Stars", "John Green", "YA", "2012"],
  ["The Founder's Dilemmas", "Noam Wasserman", "Business", "2012"],
  ["The Universe in Zero Words", "Dana Mackenzie", "Popular Science", "2012"],
  ["24/7: Late Capitalism and the Ends of Sleep", "Jonathan Crary", "Nonfiction", "2013"],
  ["Avengers: The Complete Collection", "Jonathan Hickman", "Graphic Novel", "2013"],
  ["Eleven Rings", "Phil Jackson", "Sports / Memoir", "2013"],
  ["Fantastic Four: The Complete Collection", "Jonathan Hickman", "Graphic Novel", "2013"],
  ["MIND MGMT Field Report 1", "Matt Kindt", "Graphic Novel", "2013"],
  ["The Humans", "Matt Haig", "Science Fiction", "2013"],
  ["The Ocean at the End of the Lane", "Neil Gaiman", "Fantasy", "2013"],
  ["Who Asked You?", "Terry McMillan", "Fiction", "2013"],
  ["All the Light We Cannot See", "Anthony Doerr", "Historical Fiction", "2014"],
  ["Annihilation", "Jeff VanderMeer", "Science Fiction", "2014"],
  ["MIND MGMT Field Report 2", "Matt Kindt", "Graphic Novel", "2014"],
  ["Red Rising", "Pierce Brown", "Science Fiction", "2014"],
  ["Station Eleven", "Emily St. John Mandel", "Science Fiction", "2014"],
  ["The Hard Thing About Hard Things", "Ben Horowitz", "Business", "2014"],
  ["The Shadow of What Was Lost", "James Islington", "Fantasy", "2014"],
  ["Before the Coffee Gets Cold", "Toshikazu Kawaguchi", "Fiction", "2015"],
  ["Children of Time", "Adrian Tchaikovsky", "Science Fiction", "2015"],
  ["Go Set a Watchman", "Harper Lee", "Fiction", "2015"],
  ["Golden Son", "Pierce Brown", "Science Fiction", "2015"],
  ["MIND MGMT Field Report 3", "Matt Kindt", "Graphic Novel", "2015"],
  ["Secret Wars", "Jonathan Hickman", "Graphic Novel", "2015"],
  ["The Girl in the Spider's Web", "David Lagercrantz", "Crime Thriller", "2015"],
  ["The Girl on the Train", "Paula Hawkins", "Thriller", "2015"],
  ["The Odd Woman and the City", "Vivian Gornick", "Memoir", "2015"],
  ["The Sympathizer", "Viet Thanh Nguyen", "Literary Fiction", "2015"],
  ["101 Essays That Will Change the Way You Think", "Brianna Wiest", "Self-Help", "2016"],
  ["80,000 Hours", "Benjamin Todd", "Career / Nonfiction", "2016"],
  ["A Girl's Story", "Annie Ernaux", "Memoir", "2016"],
  ["Dark Matter", "Blake Crouch", "Science Fiction", "2016"],
  ["Designing Your Life", "Bill Burnett and Dave Evans", "Self-Help", "2016"],
  ["Hidden Figures", "Margot Lee Shetterly", "Nonfiction / History", "2016"],
  ["It Ends with Us", "Colleen Hoover", "Romance", "2016"],
  ["Morning Star", "Pierce Brown", "Science Fiction", "2016"],
  ["Scythe", "Neal Shusterman", "YA Science Fiction", "2016"],
  ["The Lonely City", "Olivia Laing", "Nonfiction", "2016"],
  ["The Paper Menagerie and Other Stories", "Ken Liu", "Science Fiction (stories)", "2016"],
  ["The Simple Path to Wealth", "JL Collins", "Personal Finance", "2016"],
  ["We Are Legion (We Are Bob)", "Dennis E. Taylor", "Science Fiction", "2016"],
  ["All Systems Red", "Martha Wells", "Science Fiction", "2017"],
  ["An Echo of Things to Come", "James Islington", "Fantasy", "2017"],
  ["Artemis", "Andy Weir", "Science Fiction", "2017"],
  ["Designing Data-Intensive Applications", "Martin Kleppmann", "Technology", "2017"],
  ["How to Stop Time", "Matt Haig", "Fiction", "2017"],
  ["New York 2140", "Kim Stanley Robinson", "Science Fiction", "2017"],
  ["Tales from the Cafe", "Toshikazu Kawaguchi", "Fiction", "2017"],
  ["The End We Start From", "Megan Hunter", "Fiction", "2017"],
  ["The Girl Who Takes an Eye for an Eye", "David Lagercrantz", "Crime Thriller", "2017"],
  ["The Idiot", "Elif Batuman", "Literary Fiction", "2017"],
  ["The Manager's Path", "Camille Fournier", "Technology", "2017"],
  ["The Short Story of Art", "Susie Hodge", "Art", "2017"],
  ["Why Buddhism Is True", "Robert Wright", "Nonfiction / Religion", "2017"],
  ["Atomic Habits", "James Clear", "Self-Help", "2018"],
  ["Before Your Memory Fades", "Toshikazu Kawaguchi", "Fiction", "2018"],
  ["Fire and Blood", "George R. R. Martin", "Fantasy", "2018"],
  ["How Democracies Die", "Steven Levitsky and Daniel Ziblatt", "Politics", "2018"],
  ["Iron Gold", "Pierce Brown", "Science Fiction", "2018"],
  ["Normal People", "Sally Rooney", "Literary Fiction", "2018"],
  ["Severance", "Ling Ma", "Literary Fiction", "2018"],
  ["Short Stories in French", "Olly Richards", "Language Learning", "2018"],
  ["The 7 1/2 Deaths of Evelyn Hardcastle", "Stuart Turton", "Mystery", "2018"],
  ["The Complete Metal Gear Solid", "Oprisko and Wood", "Graphic Novel", "2018"],
  ["The Next Person You Meet in Heaven", "Mitch Albom", "Fiction", "2018"],
  ["Thunderhead", "Neal Shusterman", "YA Science Fiction", "2018"],
  ["Where the Crawdads Sing", "Delia Owens", "Literary Fiction", "2018"],
  ["10 Minutes 38 Seconds in This Strange World", "Elif Shafak", "Literary Fiction", "2019"],
  ["101 Conversations in Intermediate French", "Olly Richards", "Language Learning", "2019"],
  ["Anxious People", "Fredrik Backman", "Fiction", "2019"],
  ["Dark Age", "Pierce Brown", "Science Fiction", "2019"],
  ["Everything Is F*cked", "Mark Manson", "Self-Help", "2019"],
  ["Exhalation", "Ted Chiang", "Science Fiction (stories)", "2019"],
  ["In the Dream House", "Carmen Maria Machado", "Memoir", "2019"],
  ["Maybe You Should Talk to Someone", "Lori Gottlieb", "Memoir", "2019"],
  ["Recursion", "Blake Crouch", "Science Fiction", "2019"],
  ["Someone Who Will Love You in All Your Damaged Glory", "Raphael Bob-Waksberg", "Short Stories", "2019"],
  ["Strange Planet", "Nathan W. Pyle", "Comics", "2019"],
  ["Supermarket", "Bobby Hall (Logic)", "Thriller", "2019"],
  ["Talking to Strangers", "Malcolm Gladwell", "Nonfiction / Psychology", "2019"],
  ["The Light of All That Falls", "James Islington", "Fantasy", "2019"],
  ["The Toll", "Neal Shusterman", "YA Science Fiction", "2019"],
  ["This Is How You Lose the Time War", "Amal El-Mohtar and Max Gladstone", "Science Fiction", "2019"],
  ["To Be Taught, If Fortunate", "Becky Chambers", "Science Fiction", "2019"],
  ["Bettina Rheims (Taschen 40th Anniversary)", "Bettina Rheims", "Photography", "2020"],
  ["Demon in White", "Christopher Ruocchio", "Science Fiction", "2020"],
  ["Die with Zero", "Bill Perkins", "Personal Finance", "2020"],
  ["Dungeon Crawler Carl", "Matt Dinniman", "LitRPG / Fantasy", "2020"],
  ["Ghosts", "Dolly Alderton", "Fiction", "2020"],
  ["Piranesi", "Susanna Clarke", "Fantasy", "2020"],
  ["Stranger Planet", "Nathan W. Pyle", "Comics", "2020"],
  ["The Ballad of Songbirds and Snakes", "Suzanne Collins", "YA Dystopian", "2020"],
  ["The City We Became", "N. K. Jemisin", "Fantasy", "2020"],
  ["The Glass Hotel", "Emily St. John Mandel", "Literary Fiction", "2020"],
  ["The Invisible Life of Addie LaRue", "V. E. Schwab", "Fantasy", "2020"],
  ["The Midnight Library", "Matt Haig", "Fiction", "2020"],
  ["The Ministry for the Future", "Kim Stanley Robinson", "Science Fiction", "2020"],
  ["The Thursday Murder Club", "Richard Osman", "Mystery", "2020"],
  ["101 French Short Stories", "Dylane Moreau", "Language Learning", "2021"],
  ["A Psalm for the Wild-Built", "Becky Chambers", "Science Fiction", "2021"],
  ["Before We Say Goodbye", "Toshikazu Kawaguchi", "Fiction", "2021"],
  ["Dopamine Nation", "Anna Lembke", "Nonfiction / Psychology", "2021"],
  ["Extraordinary", "V. E. Schwab", "Graphic Novel", "2021"],
  ["How to Not Die Alone", "Logan Ury", "Self-Help", "2021"],
  ["Life in Technicolor: A Celebration of Coldplay", "Debs Wild", "Music", "2021"],
  ["People We Meet on Vacation", "Emily Henry", "Romance", "2021"],
  ["Project Hail Mary", "Andy Weir", "Science Fiction", "2021"],
  ["Several People Are Typing", "Calvin Kasulke", "Fiction", "2021"],
  ["Small Things Like These", "Claire Keegan", "Literary Fiction", "2021"],
  ["Staff Engineer", "Will Larson", "Technology", "2021"],
  ["Strange Houses", "Uketsu", "Mystery", "2021"],
  ["The Hill We Climb", "Amanda Gorman", "Poetry", "2021"],
  ["The Ninth Metal", "Benjamin Percy", "Science Fiction", "2021"],
  ["Think Again", "Adam Grant", "Nonfiction / Psychology", "2021"],
  ["A Prayer for the Crown-Shy", "Becky Chambers", "Science Fiction", "2022"],
  ["Cultural Treasures of the World", "DK", "Reference", "2022"],
  ["Everyone in My Family Has Killed Someone", "Benjamin Stevenson", "Mystery", "2022"],
  ["How High We Go in the Dark", "Sequoia Nagamatsu", "Science Fiction", "2022"],
  ["It Starts with Us", "Colleen Hoover", "Romance", "2022"],
  ["Lapvona", "Ottessa Moshfegh", "Literary Fiction", "2022"],
  ["Sea of Tranquility", "Emily St. John Mandel", "Science Fiction", "2022"],
  ["Strange Pictures", "Uketsu", "Mystery", "2022"],
  ["The Mountain in the Sea", "Ray Nayler", "Science Fiction", "2022"],
  ["The Unfamiliar Garden", "Benjamin Percy", "Science Fiction", "2022"],
  ["Falling Back in Love with Being Human", "Kai Cheng Thom", "Poetry", "2023"],
  ["Good Material", "Dolly Alderton", "Fiction", "2023"],
  ["How to Know a Person", "David Brooks", "Nonfiction", "2023"],
  ["How to Win at Chess", "Levy Rozman", "Games", "2023"],
  ["In Charge", "Arin N. Reeves", "Self-Help", "2023"],
  ["Maya", "Anand Gandhi and Zain Memon", "Science Fiction", "2023"],
  ["None of This Is True", "Lisa Jewell", "Thriller", "2023"],
  ["Orbital", "Samantha Harvey", "Literary Fiction", "2023"],
  ["System Collapse", "Martha Wells", "Science Fiction", "2023"],
  ["The Fragile Threads of Power", "V. E. Schwab", "Fantasy", "2023"],
  ["The Heaven and Earth Grocery Store", "James McBride", "Literary Fiction", "2023"],
  ["The Last Word", "Taylor Adams", "Thriller", "2023"],
  ["The Unworthy", "Agustina Bazterrica", "Horror", "2023"],
  ["The Will of the Many", "James Islington", "Fantasy", "2023"],
  ["Beautyland", "Marie-Helene Bertino", "Literary Fiction", "2024"],
  ["Help Wanted", "Adelle Waldman", "Fiction", "2024"],
  ["Intermezzo", "Sally Rooney", "Literary Fiction", "2024"],
  ["Love Life", "Matthew Hussey", "Self-Help", "2024"],
  ["Million Dollar Weekend", "Noah Kagan", "Business", "2024"],
  ["Mona's Eyes", "Thomas Schlesser", "Fiction", "2024"],
  ["Rejection", "Tony Tulathimutte", "Literary Fiction", "2024"],
  ["Stranger in Love", "Teymour Shahabi", "Fiction", "2024"],
  ["The Book of Elsewhere", "Keanu Reeves and China Mieville", "Fantasy", "2024"],
  ["The Fellowship of Puzzlemakers", "Samuel Burr", "Fiction", "2024"],
  ["The Life Impossible", "Matt Haig", "Fiction", "2024"],
  ["The Ministry of Time", "Kaliane Bradley", "Science Fiction", "2024"],
  ["The Wedding People", "Alison Espach", "Literary Fiction", "2024"],
  ["We Solve Murders", "Richard Osman", "Mystery", "2024"],
  ["Alchemy of Secrets", "Stephanie Garber", "Fantasy", "2025"],
  ["All the Water in the World", "Eiren Caffall", "Fiction", "2025"],
  ["Angel Down", "Daniel Kraus", "Horror", "2025"],
  ["Fight Oligarchy", "Bernie Sanders", "Politics", "2025"],
  ["Heart the Lover", "Lily King", "Literary Fiction", "2025"],
  ["Katabasis", "R. F. Kuang", "Fantasy", "2025"],
  ["Of Monsters and Mainframes", "Barbara Truelove", "Science Fiction", "2025"],
  ["Red City", "Marie Lu", "Fantasy", "2025"],
  ["Sunrise on the Reaping", "Suzanne Collins", "YA Dystopian", "2025"],
  ["The Cat Who Saved the Library", "Sosuke Natsukawa", "Fiction", "2025"],
  ["The Raven Scholar", "Antonia Hodgson", "Fantasy", "2025"],
  ["The Secret of Secrets", "Dan Brown", "Thriller", "2025"],
  ["The Strength of the Few", "James Islington", "Fantasy", "2025"],
  ["The Unmapping", "Denise S. Robbins", "Fiction", "2025"],
  ["Wild Dark Shore", "Charlotte McConaghy", "Literary Fiction", "2025"],
  ["The Midnight Train", "Matt Haig", "Fiction", "2026"],
  ["Entrepreneurship and Startups (HBR)", "Harvard Business Review", "Business", "2018"]
];
